---
plugboard:
  P: Y
  H: V
  S: Q
  D: U
  T: W
  L: Z
  K: E
  A: N
  R: J
  I: X
rotors: !ruby/object:BadBombe::Drums
  drums:
  - - 22
    - 1
    - 21
    - 17
    - 6
    - 19
    - 5
    - 11
    - 15
    - 2
    - 9
    - 20
    - 12
    - 3
    - 8
    - 16
    - 25
    - 4
    - 10
    - 18
    - 23
    - 7
    - 0
    - 24
    - 14
    - 13
  - - 20
    - 14
    - 2
    - 4
    - 23
    - 19
    - 5
    - 8
    - 17
    - 22
    - 10
    - 13
    - 18
    - 15
    - 3
    - 9
    - 24
    - 21
    - 1
    - 6
    - 7
    - 11
    - 25
    - 0
    - 12
    - 16
  - - 15
    - 24
    - 14
    - 16
    - 25
    - 5
    - 6
    - 8
    - 12
    - 2
    - 23
    - 9
    - 21
    - 18
    - 7
    - 10
    - 20
    - 19
    - 1
    - 3
    - 0
    - 22
    - 4
    - 11
    - 13
    - 17
reflector:
  5: 7
  17: 1
  23: 19
  9: 0
  10: 8
  3: 25
  6: 11
  21: 18
  2: 13
  20: 12
  14: 22
  24: 15
  4: 16
letters:
- A
- B
- C
- D
- E
- F
- G
- H
- I
- J
- K
- L
- M
- N
- O
- P
- Q
- R
- S
- T
- U
- V
- W
- X
- Y
- Z
